### PR TITLE
migrate to ga and setup triggers

### LINKED ISSUE #15: Switch to GA API
Healthcare GA API is available, we should use that over beta.

### PR DESCRIPTION
**Pull request by umairidris**
Fix #15

### CODE REVIEW

**Comment by xingao267** [comment]
@morgante how can we set up the Cloud Build trigger to auto run the two job under `build/` folder?

**Comment by bharathkkb** [comment]
@xingao267 here is an example PR
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/646

**Comment by umairidris** [comment]
Thanks Bharath! Sent https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/709

**Pull request merged**
